"""add policy_chunks table

Revision ID: cb4ac97d0b71
Revises: 8af762e42426
Create Date: 2026-08-03 13:25:30.911638

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

from dealership_agent.config import get_settings

# revision identifiers, used by Alembic.
revision: str = "cb4ac97d0b71"
down_revision: str | Sequence[str] | None = "8af762e42426"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _app_role_name() -> str:
    settings = get_settings()
    if not settings.app_db_user:
        raise RuntimeError("APP_DB_USER must be set to grant policy_chunks access.")
    return settings.app_db_user


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doc_slug", sa.String(length=128), nullable=False),
        sa.Column("doc_title", sa.String(length=256), nullable=False),
        sa.Column("section_heading", sa.String(length=256), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_superseded", sa.Boolean(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policy_chunks_doc_slug"), "policy_chunks", ["doc_slug"], unique=False)
    op.create_index(
        "ix_policy_chunks_embedding_hnsw",
        "policy_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###

    # Public catalog data, same as vehicles/vehicle_embeddings: read-only
    # for the app role, no RLS.
    op.execute(f"GRANT SELECT ON policy_chunks TO {_app_role_name()}")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(f"REVOKE ALL PRIVILEGES ON policy_chunks FROM {_app_role_name()}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_policy_chunks_embedding_hnsw",
        table_name="policy_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_policy_chunks_doc_slug"), table_name="policy_chunks")
    op.drop_table("policy_chunks")
    # ### end Alembic commands ###
