"""initial schema

Revision ID: cbd3d488305d
Revises:
Create Date: 2026-08-03 01:55:56.416279

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbd3d488305d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_ref", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_customers_external_ref"), "customers", ["external_ref"], unique=True)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_ref", sa.String(length=64), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("trim", sa.String(length=128), nullable=True),
        sa.Column("body_style", sa.String(length=32), nullable=True),
        sa.Column("fuel_type", sa.String(length=32), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
        sa.Column("price_low", sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
        sa.Column("price_high", sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
        sa.Column("seller_state", sa.String(length=2), nullable=True),
        sa.Column("description_raw", sa.Text(), nullable=True),
        sa.Column("description_clean", sa.Text(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_external_ref"), "vehicles", ["external_ref"], unique=True)
    op.create_index(op.f("ix_vehicles_make"), "vehicles", ["make"], unique=False)
    op.create_index(op.f("ix_vehicles_model"), "vehicles", ["model"], unique=False)
    op.create_table(
        "escalations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_escalations_customer_id"), "escalations", ["customer_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_ref", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "IN_PREPARATION",
                "READY_FOR_DELIVERY",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expected_delivery_date", sa.DateTime(), nullable=True),
        sa.Column("actual_delivery_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_order_ref"), "orders", ["order_ref"], unique=True)
    op.create_index(op.f("ix_orders_vehicle_id"), "orders", ["vehicle_id"], unique=False)
    op.create_table(
        "test_drive_bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_ref", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("REQUESTED", "CONFIRMED", "COMPLETED", "CANCELLED", name="test_drive_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_drive_bookings_booking_ref"),
        "test_drive_bookings",
        ["booking_ref"],
        unique=True,
    )
    op.create_index(
        op.f("ix_test_drive_bookings_customer_id"),
        "test_drive_bookings",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_drive_bookings_vehicle_id"),
        "test_drive_bookings",
        ["vehicle_id"],
        unique=False,
    )
    op.create_table(
        "vehicle_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vehicle_embeddings_embedding_hnsw",
        "vehicle_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_vehicle_embeddings_vehicle_id"), "vehicle_embeddings", ["vehicle_id"], unique=False
    )
    op.create_table(
        "order_status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "IN_PREPARATION",
                "READY_FOR_DELIVERY",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="order_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "IN_PREPARATION",
                "READY_FOR_DELIVERY",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("changed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"), "order_status_history", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_status_history_order_id"), table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(op.f("ix_vehicle_embeddings_vehicle_id"), table_name="vehicle_embeddings")
    op.drop_index(
        "ix_vehicle_embeddings_embedding_hnsw",
        table_name="vehicle_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("vehicle_embeddings")
    op.drop_index(op.f("ix_test_drive_bookings_vehicle_id"), table_name="test_drive_bookings")
    op.drop_index(op.f("ix_test_drive_bookings_customer_id"), table_name="test_drive_bookings")
    op.drop_index(op.f("ix_test_drive_bookings_booking_ref"), table_name="test_drive_bookings")
    op.drop_table("test_drive_bookings")
    op.drop_index(op.f("ix_orders_vehicle_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_ref"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_escalations_customer_id"), table_name="escalations")
    op.drop_table("escalations")
    op.drop_index(op.f("ix_vehicles_model"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_make"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_external_ref"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_customers_external_ref"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
