"""Audit the price distribution in the vehicles table.

Price is a derived KBB fair-price midpoint (see docs/DATA_PROFILE.md,
docs/DATA_CLEANING.md) - it has never been validated for plausibility.
This reports the distribution, flags likely data errors, and checks one
specific listing (2015 Chevrolet Traverse LS at $4,527.5) surfaced during
manual testing in an earlier session.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import structlog
from sqlalchemy import create_engine, text

from dealership_agent.config import get_settings

structlog.configure(processors=[structlog.processors.JSONRenderer()])
logger = structlog.get_logger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"

LOW_PRICE_THRESHOLD = 2000
HIGH_PRICE_THRESHOLD = 200_000
WIDE_RANGE_RATIO = 3.0
N_LOWEST = 20

QUERY = text(
    """
    SELECT id, external_ref, year, make, model, trim, mileage,
           price, price_low, price_high, is_price_reliable
    FROM vehicles
    """
)


def load_vehicles() -> pd.DataFrame:
    settings = get_settings()
    engine = create_engine(settings.database_url)
    with engine.connect() as conn:
        return pd.read_sql(QUERY, conn)


def _percentiles(price: pd.Series) -> dict[str, float]:
    return {
        "min": float(price.min()),
        "p1": float(price.quantile(0.01)),
        "p5": float(price.quantile(0.05)),
        "p25": float(price.quantile(0.25)),
        "median": float(price.median()),
        "p75": float(price.quantile(0.75)),
        "p95": float(price.quantile(0.95)),
        "p99": float(price.quantile(0.99)),
        "max": float(price.max()),
    }


def audit(df: pd.DataFrame) -> dict[str, object]:
    priced = df[df["price"].notna()].copy()
    price = priced["price"]

    stats = _percentiles(price)
    # Percentiles among is_price_reliable rows only - the numbers that
    # should actually be used downstream (e.g. Part C's router thresholds
    # for "cheap"/"mid-range"/"premium"), since `stats` above still
    # includes the $0.00 sentinel rows and understates every percentile
    # below roughly the 5th.
    reliable_price = priced.loc[priced["is_price_reliable"], "price"]
    reliable_stats = _percentiles(reliable_price)
    below_low = int((price < LOW_PRICE_THRESHOLD).sum())
    above_high = int((price > HIGH_PRICE_THRESHOLD).sum())
    unreliable_count = int((~priced["is_price_reliable"]).sum())

    lowest = priced.nsmallest(N_LOWEST, "price")[
        ["year", "make", "model", "mileage", "price_low", "price_high", "price"]
    ]

    inverted_range = priced[priced["price_high"] < priced["price_low"]]
    wide_range = priced[
        (priced["price_low"] > 0) & (priced["price_high"] / priced["price_low"] > WIDE_RANGE_RATIO)
    ]

    traverse = df[
        (df["make"] == "Chevrolet")
        & (df["model"] == "Traverse")
        & (df["trim"] == "LS")
        & (df["year"] == 2015)
    ]

    return {
        "total_rows": len(df),
        "priced_rows": len(priced),
        "stats": stats,
        "reliable_stats": reliable_stats,
        "unreliable_count": unreliable_count,
        "below_low_threshold": below_low,
        "above_high_threshold": above_high,
        "lowest": lowest,
        "inverted_range": inverted_range,
        "wide_range": wide_range,
        "traverse_matches": traverse,
    }


def _markdown_table(df: pd.DataFrame, columns: list[str], float_cols: set[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join("---" for _ in columns) + " |"
    rows = [header, separator]
    for _, row in df[columns].iterrows():
        cells = []
        for col in columns:
            value = row[col]
            cells.append(f"{value:,.2f}" if col in float_cols else str(value))
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join(rows)


def _write_report(result: dict[str, object], out_path: Path) -> None:
    stats = result["stats"]
    assert isinstance(stats, dict)  # noqa: S101 -- internal invariant, not a test
    reliable_stats = result["reliable_stats"]
    assert isinstance(reliable_stats, dict)  # noqa: S101
    lowest = result["lowest"]
    assert isinstance(lowest, pd.DataFrame)  # noqa: S101
    inverted_range = result["inverted_range"]
    assert isinstance(inverted_range, pd.DataFrame)  # noqa: S101
    wide_range = result["wide_range"]
    assert isinstance(wide_range, pd.DataFrame)  # noqa: S101
    traverse_matches = result["traverse_matches"]
    assert isinstance(traverse_matches, pd.DataFrame)  # noqa: S101

    lines = [
        "# Price Data Audit\n",
        "Generated by `data/scripts/audit_prices.py`. `price` is a derived "
        "KBB fair-price midpoint, never the actual sale price (see "
        "docs/DATA_PROFILE.md) - this checks whether that derived value is "
        "plausible.\n",
        "## Distribution (raw, includes the $0.00 sentinel - see Decision below)\n",
        f"- Rows total: **{result['total_rows']:,}**, with a non-null price: "
        f"**{result['priced_rows']:,}**",
        f"- min: **${stats['min']:,.2f}**",
        f"- p1: **${stats['p1']:,.2f}**",
        f"- p5: **${stats['p5']:,.2f}**",
        f"- p25: **${stats['p25']:,.2f}**",
        f"- median: **${stats['median']:,.2f}**",
        f"- p75: **${stats['p75']:,.2f}**",
        f"- p95: **${stats['p95']:,.2f}**",
        f"- p99: **${stats['p99']:,.2f}**",
        f"- max: **${stats['max']:,.2f}**\n",
        f"- Below ${LOW_PRICE_THRESHOLD:,}: **{result['below_low_threshold']:,}** rows",
        f"- Above ${HIGH_PRICE_THRESHOLD:,}: **{result['above_high_threshold']:,}** rows\n",
        "## Distribution (is_price_reliable=true only - use these for downstream thresholds)\n",
        f"- Rows: **{result['priced_rows'] - result['unreliable_count']:,}** "  # type: ignore[operator]
        f"(excludes **{result['unreliable_count']:,}** unreliable rows)",
        f"- min: **${reliable_stats['min']:,.2f}**",
        f"- p1: **${reliable_stats['p1']:,.2f}**",
        f"- p5: **${reliable_stats['p5']:,.2f}**",
        f"- p25: **${reliable_stats['p25']:,.2f}**",
        f"- median: **${reliable_stats['median']:,.2f}**",
        f"- p75: **${reliable_stats['p75']:,.2f}**",
        f"- p95: **${reliable_stats['p95']:,.2f}**",
        f"- p99: **${reliable_stats['p99']:,.2f}**",
        f"- max: **${reliable_stats['max']:,.2f}**\n",
        f"## {N_LOWEST} lowest-priced listings\n",
        "| Year | Make | Model | Mileage | price_low | price_high | price |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for _, row in lowest.iterrows():
        lines.append(
            f"| {row['year']} | {row['make']} | {row['model']} | "
            f"{row['mileage']:,} | {row['price_low']:,.2f} | "
            f"{row['price_high']:,.2f} | {row['price']:,.2f} |"
        )

    lines += [
        "",
        "## Inverted ranges (price_high < price_low)\n",
        f"**{len(inverted_range)}** rows found.",
    ]
    if len(inverted_range):
        cols = ["year", "make", "model", "mileage", "price_low", "price_high"]
        lines.append(_markdown_table(inverted_range, cols, float_cols={"price_low", "price_high"}))
    lines.append("")

    lines += [
        f"## Wide ranges (price_high / price_low > {WIDE_RANGE_RATIO:.0f}x)\n",
        f"**{len(wide_range)}** rows found.",
    ]
    if len(wide_range):
        cols = ["year", "make", "model", "mileage", "price_low", "price_high"]
        lines.append(
            _markdown_table(wide_range.head(20), cols, float_cols={"price_low", "price_high"})
        )
    lines.append("")

    lines += [
        "## 2015 Chevrolet Traverse LS check\n",
        f"**{len(traverse_matches)}** matching row(s) found for "
        "year=2015, make=Chevrolet, model=Traverse, trim=LS.\n",
    ]
    if len(traverse_matches):
        cols = ["external_ref", "mileage", "price_low", "price_high", "price"]
        lines.append(
            _markdown_table(traverse_matches, cols, float_cols={"price_low", "price_high", "price"})
        )
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DOCS_DIR / "DATA_PRICE_AUDIT.md"))
    args = parser.parse_args()

    logger.info("loading_vehicles")
    df = load_vehicles()
    logger.info("vehicles_loaded", rows=len(df))

    result = audit(df)
    logger.info(
        "audit_complete",
        priced_rows=result["priced_rows"],
        below_low_threshold=result["below_low_threshold"],
        above_high_threshold=result["above_high_threshold"],
        inverted_range_count=len(result["inverted_range"]),  # type: ignore[arg-type]
        wide_range_count=len(result["wide_range"]),  # type: ignore[arg-type]
    )

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    _write_report(result, out_path)
    logger.info("report_written", path=str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
