"""Audit the boilerplate-stripping step of clean_listings.py.

28,766 removals across 23,597 listings is high enough to be suspicious.
This reproduces the pipeline up to (but not including) boilerplate
stripping, then reports exactly what would be stripped and why, so a human
can judge whether it is dealer marketing or real product information.
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path
from typing import TypedDict

import pandas as pd
import structlog
from clean_listings import (
    BOILERPLATE_MIN_OCCURRENCES,
    RAW_DIR,
    _load_raw,
    compute_price,
    find_near_duplicates,
    redact_descriptions,
    segment_counts,
    strip_boilerplate,
)

structlog.configure(processors=[structlog.processors.JSONRenderer()])
logger = structlog.get_logger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"

TOP_N_SEGMENTS = 50
SAMPLE_SIZE = 10
SAMPLE_TRUNCATE = 500
HEAVY_LOSS_THRESHOLD = 0.40
RANDOM_SEED = 42


class AuditStats(TypedDict):
    rows: int
    top_segments: list[tuple[str, int]]
    samples: list[tuple[str, str]]
    avg_length_before: float
    avg_length_after: float
    heavy_loss_count: int
    heavy_loss_pct: float


def _prepare_pre_boilerplate(df: pd.DataFrame) -> pd.DataFrame:
    """Reproduce clean_listings.clean() up to (not including) boilerplate
    stripping, so segment frequency reflects exactly what strip_boilerplate
    sees at cleaning time."""
    df = compute_price(df)
    df["description_raw"] = df["description"]
    redacted, _ = redact_descriptions(df["description"])
    df["description_clean"] = redacted
    df["make"] = df["makeName"]
    df["model"] = df["modelName"]
    duplicate_index = find_near_duplicates(df)
    return df.drop(index=duplicate_index)


def audit(df: pd.DataFrame) -> AuditStats:
    df = _prepare_pre_boilerplate(df)
    pre_strip_texts = df["description_clean"].fillna("")

    counts = segment_counts(pre_strip_texts)
    boilerplate = {seg: c for seg, c in counts.items() if c >= BOILERPLATE_MIN_OCCURRENCES}
    top_segments = sorted(boilerplate.items(), key=lambda kv: -kv[1])[:TOP_N_SEGMENTS]

    cleaned_texts, _, _ = strip_boilerplate(pre_strip_texts)

    before_lengths = pre_strip_texts.str.len()
    after_lengths = cleaned_texts.str.len()
    avg_before = float(before_lengths.mean())
    avg_after = float(after_lengths.mean())

    nonzero = before_lengths > 0
    loss_fraction = 1 - (after_lengths[nonzero] / before_lengths[nonzero])
    heavy_loss_count = int((loss_fraction > HEAVY_LOSS_THRESHOLD).sum())

    rng = random.Random(RANDOM_SEED)  # noqa: S311 -- reproducible sampling, not crypto
    sample_positions = rng.sample(range(len(df)), min(SAMPLE_SIZE, len(df)))
    samples = [
        (
            str(pre_strip_texts.iloc[pos])[:SAMPLE_TRUNCATE],
            str(cleaned_texts.iloc[pos])[:SAMPLE_TRUNCATE],
        )
        for pos in sample_positions
    ]

    return {
        "rows": len(df),
        "top_segments": top_segments,
        "samples": samples,
        "avg_length_before": avg_before,
        "avg_length_after": avg_after,
        "heavy_loss_count": heavy_loss_count,
        "heavy_loss_pct": heavy_loss_count / len(df) * 100,
    }


def _write_report(stats: AuditStats, out_path: Path) -> None:
    lines = [
        "# Data Cleaning Audit: Boilerplate Stripping\n",
        "Generated by `data/scripts/audit_cleaning.py`. Reproduces the "
        "cleaning pipeline up to (not including) boilerplate stripping, so "
        "these numbers reflect exactly what `strip_boilerplate()` removes.\n",
        "## Length impact\n",
        f"- Average length before: **{stats['avg_length_before']:.0f} characters**",
        f"- Average length after: **{stats['avg_length_after']:.0f} characters**",
        f"- Listings that lost more than {HEAVY_LOSS_THRESHOLD:.0%} of their "
        f"characters: **{stats['heavy_loss_count']:,}** "
        f"({stats['heavy_loss_pct']:.1f}% of {stats['rows']:,})\n",
        f"## Top {len(stats['top_segments'])} most frequently removed segments\n",
        "| # | Occurrences | Segment |",
        "| --- | --- | --- |",
    ]
    for i, (segment, count) in enumerate(stats["top_segments"], start=1):
        escaped = segment.replace("|", "\\|")[:160]
        lines.append(f"| {i} | {count:,} | `{escaped}` |")

    lines += [
        "",
        f"## {len(stats['samples'])} randomly sampled listings, before/after "
        f"(truncated to {SAMPLE_TRUNCATE} chars)\n",
    ]
    for i, (before, after) in enumerate(stats["samples"], start=1):
        lines += [
            f"### Sample {i}\n",
            "**Before:**",
            f"> {before}\n",
            "**After:**",
            f"> {after}\n",
        ]

    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw-dir", default=str(RAW_DIR))
    parser.add_argument("--out", default=str(DOCS_DIR / "DATA_CLEANING_AUDIT.md"))
    args = parser.parse_args()

    logger.info("loading_raw_dataset", raw_dir=args.raw_dir)
    df = _load_raw(Path(args.raw_dir))
    logger.info("raw_dataset_loaded", rows=len(df))

    stats = audit(df)
    logger.info(
        "audit_complete",
        rows=stats["rows"],
        top_segments_found=len(stats["top_segments"]),
        avg_length_before=stats["avg_length_before"],
        avg_length_after=stats["avg_length_after"],
        heavy_loss_count=stats["heavy_loss_count"],
    )

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    _write_report(stats, out_path)
    logger.info("report_written", path=str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
