"""Profile the downloaded car-listings dataset and write docs/DATA_PROFILE.md.

Reads the raw parquet/CSV files produced by download_listings.py, computes
per-column statistics, and reports which fields are redacted (contain the
literal string "[PREMIUM]"), so downstream tool/schema design knows which
fields are real and usable versus masked in this data tier.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import structlog

structlog.configure(processors=[structlog.processors.JSONRenderer()])
logger = structlog.get_logger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
RAW_DIR = REPO_ROOT / "data" / "raw"
DOCS_DIR = REPO_ROOT / "docs"

REDACTED_MARKER = "[PREMIUM]"
PROSE_MIN_AVG_CHARS = 200
USABLE_FILTER_CANDIDATES = {
    "price": ["salePrice", "kbbFairPriceLow", "kbbFairPriceHigh", "msrp", "price"],
    "year": ["year"],
    "mileage": ["mileage"],
    "make": ["makeName", "makeCode", "make"],
    "model": ["modelName", "modelCode", "model"],
    "body style": ["bodyStyle", "body_type", "body_style"],
    "fuel": ["fuelType", "fuelTypeGroup", "fuel_type", "fuel"],
}


def _load_dataset(dataset_dir: Path) -> tuple[pd.DataFrame, str]:
    parquet_files = sorted(dataset_dir.rglob("*.parquet"))
    csv_files = sorted(f for f in dataset_dir.rglob("*.csv") if f.name != "sample.csv")

    if parquet_files:
        frames = [pd.read_parquet(f) for f in parquet_files]
        return pd.concat(frames, ignore_index=True), "parquet"
    if csv_files:
        frames = [pd.read_csv(f, low_memory=False) for f in csv_files]
        return pd.concat(frames, ignore_index=True), "csv"
    raise FileNotFoundError(f"No parquet or csv files found under {dataset_dir}")


def _date_range(df: pd.DataFrame) -> str:
    for col in ("_firstSeenAt", "_lastSeenAt", "listing_date", "date", "posting_date"):
        if col in df.columns:
            parsed = pd.to_datetime(df[col], errors="coerce", utc=True)
            if parsed.notna().any():
                return f"{parsed.min()} to {parsed.max()} (via `{col}`)"
    return "unknown (no recognizable date column)"


def _example_values(series: pd.Series, n: int = 3) -> list[str]:
    non_null = series.dropna()
    examples = non_null.astype(str).unique()[:n]
    return list(examples)


def _is_redacted(series: pd.Series) -> tuple[bool, float]:
    if series.dtype != object and str(series.dtype) != "str":
        return False, 0.0
    as_str = series.astype(str)
    pct = (as_str == REDACTED_MARKER).mean() * 100
    return pct > 0, pct


def _looks_like_structured_data(values: pd.Series, sample_size: int = 200) -> bool:
    """Heuristic: JSON/array-shaped strings (e.g. `{"a": 1}`, `["x","y"]`) are
    not prose, even when long, so exclude them from prose detection."""
    sample = values.head(sample_size).str.strip()
    starts_structured = float(sample.str.startswith(("{", "[")).mean())
    return starts_structured > 0.5


def _find_prose_column(df: pd.DataFrame) -> tuple[str | None, float]:
    best_col: str | None = None
    best_avg = 0.0
    for col in df.columns:
        if df[col].dtype != object and str(df[col].dtype) != "str":
            continue
        non_redacted = df[col].dropna().astype(str)
        non_redacted = non_redacted[non_redacted != REDACTED_MARKER]
        if non_redacted.empty or _looks_like_structured_data(non_redacted):
            continue
        avg_word_count = non_redacted.str.split().str.len().mean()
        if avg_word_count < 15:
            continue
        avg_len = non_redacted.str.len().mean()
        if avg_len > best_avg:
            best_avg = avg_len
            best_col = col
    if best_col is not None and best_avg >= PROSE_MIN_AVG_CHARS:
        return best_col, best_avg
    return None, best_avg


def _usable_columns(df: pd.DataFrame) -> dict[str, str | None]:
    resolved: dict[str, str | None] = {}
    for label, candidates in USABLE_FILTER_CANDIDATES.items():
        match = next((c for c in candidates if c in df.columns), None)
        if match is not None:
            redacted, pct = _is_redacted(df[match])
            if redacted and pct > 50:
                fallback = next(
                    (
                        c
                        for c in candidates
                        if c in df.columns and c != match and not _is_redacted(df[c])[0]
                    ),
                    None,
                )
                match = fallback if fallback is not None else f"{match} (REDACTED, not usable)"
        resolved[label] = match
    return resolved


def build_report(df: pd.DataFrame, file_format: str) -> str:
    lines: list[str] = []
    lines.append("# Data Profile: Car Listings\n")
    lines.append(
        "Generated by `data/scripts/profile_listings.py`. This file documents the "
        "real shape of the source data so tool and schema design is grounded in "
        "fact, not assumption.\n"
    )

    lines.append("## Summary\n")
    lines.append(f"- Row count: **{len(df):,}**")
    lines.append(f"- File format: **{file_format}**")
    lines.append(f"- Date range: **{_date_range(df)}**")
    lines.append(f"- Column count: **{len(df.columns)}**\n")

    redacted_cols = []
    for col in df.columns:
        redacted, pct = _is_redacted(df[col])
        if redacted:
            redacted_cols.append((col, pct))

    lines.append("## Redacted columns\n")
    if redacted_cols:
        lines.append(
            f"The following columns contain the literal string `{REDACTED_MARKER}` "
            "for some or all rows in this data tier and cannot be used as real "
            "values:\n"
        )
        lines.append("| Column | % rows redacted |")
        lines.append("| --- | --- |")
        for col, pct in sorted(redacted_cols, key=lambda x: -x[1]):
            lines.append(f"| `{col}` | {pct:.1f}% |")
        lines.append("")
    else:
        lines.append("No columns contain the redacted-value token.\n")

    prose_col, prose_avg_len = _find_prose_column(df)
    lines.append("## Free-text description column\n")
    if prose_col is not None:
        fill_pct = df[prose_col].notna().mean() * 100
        lines.append(f"**Yes.** Column `{prose_col}` is free-text prose.")
        lines.append(
            f"- Average length: **{prose_avg_len:.0f} characters** (non-null, non-redacted values)"
        )
        lines.append(f"- Fill rate: {fill_pct:.1f}%")
        lines.append(
            "\nThis means listing descriptions do **not** need to be generated "
            "synthetically — real marketing copy is present in the source data.\n"
        )
    else:
        lines.append(
            "**No.** No column was found with an average length over "
            f"{PROSE_MIN_AVG_CHARS} characters. Listing descriptions would need "
            "to be generated or templated separately.\n"
        )

    lines.append("## Usable columns for structured filters\n")
    usable = _usable_columns(df)
    lines.append("| Filter | Source column | Notes |")
    lines.append("| --- | --- | --- |")
    for label, col in usable.items():
        if col is None:
            lines.append(f"| {label} | _none found_ | no candidate column present |")
        elif "REDACTED" in col:
            lines.append(f"| {label} | `{col}` | redacted in this data tier, not usable as-is |")
        else:
            redacted, pct = _is_redacted(df[col])
            note = f"redacted {pct:.0f}% of rows" if redacted else "clean"
            lines.append(f"| {label} | `{col}` | {note} |")
    lines.append("")

    lines.append("## All columns\n")
    lines.append("| Column | dtype | null % | cardinality | example values |")
    lines.append("| --- | --- | --- | --- | --- |")
    for col in df.columns:
        dtype = str(df[col].dtype)
        null_pct = df[col].isna().mean() * 100
        cardinality = df[col].nunique(dropna=True)
        examples = ", ".join(f"`{v[:40]}`" for v in _example_values(df[col]))
        lines.append(f"| `{col}` | {dtype} | {null_pct:.1f}% | {cardinality:,} | {examples} |")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dataset-dir",
        default=str(RAW_DIR / "autotrader-dataset"),
        help="Directory containing the downloaded raw dataset files",
    )
    parser.add_argument(
        "--out",
        default=str(DOCS_DIR / "DATA_PROFILE.md"),
        help="Path to write the markdown report to",
    )
    args = parser.parse_args()

    dataset_dir = Path(args.dataset_dir)
    logger.info("loading_dataset", dataset_dir=str(dataset_dir))
    df, file_format = _load_dataset(dataset_dir)
    logger.info("dataset_loaded", rows=len(df), columns=len(df.columns), file_format=file_format)

    report = build_report(df, file_format)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report)
    logger.info("report_written", path=str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
